// Constants for Action calls
export const ADD_DREAMING_ELEMENT = 'ADD_DREAMING_ELEMENT';
export const UPDATE_DREAMING_ELEMENTS = 'UPDATE_DREAMING_ELEMENTS';
export const REMOVE_DREAMING_ELEMENT = 'REMOVE_DREAMING_ELEMENT';
export const CHANGE_DREAMING_ELEMENT_ITERATION =
    'CHANGE_DREAMING_ELEMENT_ITERATION';
